AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
